# Generated by Django 2.2.10 on 2020-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200211_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tops',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=1),
        ),
    ]
