# Generated by Django 2.2.10 on 2020-02-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_menu_tops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='tops',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('l', 'Large')], default='Large', max_length=1),
        ),
    ]
