# Generated by Django 2.2.10 on 2020-02-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200212_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='tops',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=0),
        ),
    ]
