# Generated by Django 2.2.10 on 2020-02-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200212_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Sub', 'Sub'), ('Steak+Cheese', 'Steak+Cheese')], max_length=20),
        ),
    ]
