# Generated by Django 2.2.10 on 2020-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200207_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Processing', 'Processing'), ('On Route', 'On Route'), ('Delivered', 'Delivered'), ('None', '')], default='None', max_length=20),
        ),
    ]
